import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: "#f0f9ff",
          100: "#e0f2fe",
          200: "#bae6fd",
          300: "#7dd3fc",
          400: "#38bdf8",
          500: "#0ea5e9",
          600: "#0284c7",
          700: "#0369a1",
          800: "#075985",
          900: "#0c4a6e",
        },
      },
    },
  },
  safelist: [
    // Background colors
    'bg-gray-900',
    'bg-gray-800', 
    'bg-gray-950',
    'bg-white',
    'bg-indigo-600',
    'bg-indigo-700',
    'bg-purple-600',
    'bg-purple-700',
    'bg-purple-900',
    'bg-indigo-900',
    // Text colors
    'text-white',
    'text-gray-300',
    'text-gray-400',
    'text-gray-200',
    'text-indigo-400',
    'text-purple-400',
    'text-pink-400',
    // Borders
    'border-gray-700',
    'border-white/10',
    'border-purple-700',
    // Flex/Grid
    'flex',
    'flex-col',
    'items-center',
    'justify-center',
    'justify-between',
    'min-h-screen',
    'grid',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-5',
    'gap-4',
    'gap-6',
    'gap-8',
    // Spacing
    'p-4',
    'p-6',
    'px-4',
    'py-20',
    'pt-16',
    'pt-24',
    'pt-32',
    'mb-2',
    'mb-4',
    'mb-6',
    'mb-8',
    'mb-10',
    'mb-16',
    'max-w-7xl',
    'mx-auto',
    'relative',
    'absolute',
    'inset-0',
    'z-10',
    'z-50',
    // Typography
    'text-5xl',
    'text-4xl',
    'text-2xl',
    'text-xl',
    'text-lg',
    'text-sm',
    'text-xs',
    'font-bold',
    'font-semibold',
    'font-medium',
    // Misc
    'rounded-lg',
    'rounded-xl',
    'rounded-2xl',
    'rounded-full',
    'overflow-hidden',
    'transition-colors',
    'hover:bg-indigo-700',
    'hover:bg-purple-700',
    'hover:text-white',
  ],
  plugins: [],
};
export default config;
